#!/bin/bash
# ============================================================
# AI Navigation System — Bluetooth Earphone Setup Script
# Usage: bash setup_bluetooth_audio.sh <EARPHONE_MAC_ADDRESS>
# Example: bash setup_bluetooth_audio.sh AA:BB:CC:DD:EE:FF
# Run this ONCE on the Raspberry Pi as the 'pi' user (not root)
# ============================================================

set -e

MAC="${1:?ERROR: Provide earphone MAC address. Usage: $0 AA:BB:CC:DD:EE:FF}"

# Validate MAC format
if ! echo "$MAC" | grep -qE '^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$'; then
    echo "ERROR: Invalid MAC address format. Expected XX:XX:XX:XX:XX:XX"
    exit 1
fi

SINK="bluez_sink.${MAC//:/_}.a2dp_sink"

echo ""
echo "========================================="
echo " AI Navigation — Bluetooth Audio Setup"
echo "========================================="
echo " Earphone MAC : $MAC"
echo " Target Sink  : $SINK"
echo ""

# ── Step 1: Install packages ──────────────────────────────
echo "[1/6] Installing Bluetooth & audio packages..."
sudo apt update -qq
sudo apt install -y \
    bluez bluez-tools \
    pulseaudio pulseaudio-module-bluetooth \
    alsa-utils mpg123 python3-pyttsx3 \
    2>/dev/null

# ── Step 2: Enable services ───────────────────────────────
echo "[2/6] Enabling Bluetooth & PulseAudio services..."
sudo systemctl enable bluetooth
sudo systemctl start bluetooth
sudo rfkill unblock bluetooth 2>/dev/null || true
pulseaudio --start 2>/dev/null || true
sleep 2

# ── Step 3: Pair, trust, connect ─────────────────────────
echo "[3/6] Pairing and connecting earphone ($MAC)..."
echo "      >>> PUT YOUR EARPHONE IN PAIRING MODE NOW <<<"
sleep 4

bluetoothctl << EOF
power on
discoverable on
scan on
EOF

sleep 5

bluetoothctl << EOF
scan off
pair $MAC
trust $MAC
connect $MAC
quit
EOF

sleep 3
echo "    ✓ Pairing commands sent."

# ── Step 4: Set A2DP as default sink ─────────────────────
echo "[4/6] Setting Bluetooth A2DP sink as default audio output..."
pactl set-default-sink "$SINK" 2>/dev/null && \
    echo "    ✓ Default sink set to: $SINK" || \
    echo "    ⚠ Sink not ready yet — will be set on next boot via systemd service."

# ── Step 5: Create auto-connect service ──────────────────
echo "[5/6] Creating systemd auto-connect service..."

sudo tee /usr/local/bin/bt-audio-connect.sh > /dev/null << SCRIPT
#!/bin/bash
# Auto-generated by setup_bluetooth_audio.sh
# Reconnects Bluetooth earphone and sets audio sink on boot
EARPHONE_MAC="$MAC"
SINK_NAME="$SINK"

sleep 8   # Wait for bluetooth daemon and pulseaudio to settle

echo "[BT-AUTO] Connecting to earphone: \$EARPHONE_MAC"
bluetoothctl connect "\$EARPHONE_MAC" 2>/dev/null && echo "[BT-AUTO] Connected OK" || echo "[BT-AUTO] Connect failed (earphone off?)"

sleep 3

# Set as default audio sink
pactl set-default-sink "\$SINK_NAME" 2>/dev/null && \
    echo "[BT-AUTO] Sink set: \$SINK_NAME" || \
    echo "[BT-AUTO] Could not set sink. Try: pactl set-default-sink \$SINK_NAME"
SCRIPT

sudo chmod +x /usr/local/bin/bt-audio-connect.sh

sudo tee /etc/systemd/system/bt-audio.service > /dev/null << UNIT
[Unit]
Description=Bluetooth Earphone Auto-Connect for AI Navigation
After=bluetooth.service pulseaudio.service network.target
Wants=bluetooth.service

[Service]
Type=oneshot
ExecStart=/usr/local/bin/bt-audio-connect.sh
User=pi
Environment=PULSE_RUNTIME_PATH=/run/user/1000/pulse
RemainAfterExit=yes
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
UNIT

sudo systemctl daemon-reload
sudo systemctl enable bt-audio.service
echo "    ✓ systemd service 'bt-audio.service' installed and enabled."

# ── Step 6: Test TTS ──────────────────────────────────────
echo "[6/6] Testing voice output through earphone..."
sleep 2
python3 - << PYEOF
import os, sys
os.environ['AUDIODRIVER'] = 'pulse'
try:
    import pyttsx3
    engine = pyttsx3.init()
    engine.say("Bluetooth earphone connected. AI Navigation system ready.")
    engine.runAndWait()
    print("    ✓ TTS test successful — you should have heard audio.")
except Exception as e:
    print(f"    ⚠ TTS test failed: {e}")
    print("      Try: mpg123 /usr/share/sounds/alsa/Front_Center.wav")
PYEOF

# ── Summary ───────────────────────────────────────────────
echo ""
echo "============================================="
echo " ✅  Bluetooth Audio Setup Complete!"
echo "============================================="
echo " Earphone MAC    : $MAC"
echo " Audio Sink      : $SINK"
echo " Auto-connect    : systemctl status bt-audio.service"
echo ""
echo " Useful commands:"
echo "   bluetoothctl info $MAC       # Check connection status"
echo "   pactl get-default-sink        # Verify audio sink"
echo "   pactl list sinks short        # List all sinks"
echo "   systemctl status bt-audio     # Check auto-connect service"
echo ""
echo " If earphone disconnects:"
echo "   bluetoothctl connect $MAC"
echo "   pactl set-default-sink $SINK"
echo ""
