# Eclipse Mosquitto configuration file
# See mosquitto.conf(5) for more details.

# Listener for standard MQTT over TCP
listener 1883 127.0.0.1
allow_anonymous true

# Listener for MQTT over WebSockets
listener 8083 127.0.0.1
protocol websockets
allow_anonymous true
